export const COUNTRIES: { code: string; label: string }[] = [
  { code: 'TR', label: 'Türkiye' },
  { code: 'US', label: 'Amerika Birleşik Devletleri' },
  { code: 'GB', label: 'Birleşik Krallık' },
  { code: 'DE', label: 'Almanya' },
  { code: 'FR', label: 'Fransa' },
  { code: 'NL', label: 'Hollanda' },
  { code: 'IT', label: 'İtalya' },
  { code: 'ES', label: 'İspanya' },
  { code: 'BE', label: 'Belçika' },
  { code: 'AT', label: 'Avusturya' },
  { code: 'CH', label: 'İsviçre' },
  { code: 'SE', label: 'İsveç' },
  { code: 'NO', label: 'Norveç' },
  { code: 'DK', label: 'Danimarka' },
  { code: 'FI', label: 'Finlandiya' },
  { code: 'IE', label: 'İrlanda' },
  { code: 'PT', label: 'Portekiz' },
  { code: 'GR', label: 'Yunanistan' },
  { code: 'PL', label: 'Polonya' },
  { code: 'RO', label: 'Romanya' },
  { code: 'BG', label: 'Bulgaristan' },
  { code: 'HU', label: 'Macaristan' },
  { code: 'CZ', label: 'Çekya' },
  { code: 'UA', label: 'Ukrayna' },
  { code: 'RU', label: 'Rusya' },
  { code: 'AZ', label: 'Azerbaycan' },
  { code: 'GE', label: 'Gürcistan' },
  { code: 'KZ', label: 'Kazakistan' },
  { code: 'UZ', label: 'Özbekistan' },
  { code: 'KG', label: 'Kırgızistan' },
  { code: 'AE', label: 'Birleşik Arap Emirlikleri' },
  { code: 'SA', label: 'Suudi Arabistan' },
  { code: 'QA', label: 'Katar' },
  { code: 'KW', label: 'Kuveyt' },
  { code: 'BH', label: 'Bahreyn' },
  { code: 'OM', label: 'Umman' },
  { code: 'IL', label: 'İsrail' },
  { code: 'EG', label: 'Mısır' },
  { code: 'MA', label: 'Fas' },
  { code: 'TN', label: 'Tunus' },
  { code: 'DZ', label: 'Cezayir' },
  { code: 'LY', label: 'Libya' },
  { code: 'IR', label: 'İran' },
  { code: 'IQ', label: 'Irak' },
  { code: 'SY', label: 'Suriye' },
  { code: 'LB', label: 'Lübnan' },
  { code: 'JO', label: 'Ürdün' },
  { code: 'PK', label: 'Pakistan' },
  { code: 'IN', label: 'Hindistan' },
  { code: 'BD', label: 'Bangladeş' },
  { code: 'CN', label: 'Çin' },
  { code: 'JP', label: 'Japonya' },
  { code: 'KR', label: 'Güney Kore' },
  { code: 'TW', label: 'Tayvan' },
  { code: 'HK', label: 'Hong Kong' },
  { code: 'SG', label: 'Singapur' },
  { code: 'MY', label: 'Malezya' },
  { code: 'ID', label: 'Endonezya' },
  { code: 'TH', label: 'Tayland' },
  { code: 'VN', label: 'Vietnam' },
  { code: 'PH', label: 'Filipinler' },
  { code: 'AU', label: 'Avustralya' },
  { code: 'NZ', label: 'Yeni Zelanda' },
  { code: 'CA', label: 'Kanada' },
  { code: 'MX', label: 'Meksika' },
  { code: 'BR', label: 'Brezilya' },
  { code: 'AR', label: 'Arjantin' },
  { code: 'CL', label: 'Şili' },
  { code: 'CO', label: 'Kolombiya' },
  { code: 'PE', label: 'Peru' },
  { code: 'ZA', label: 'Güney Afrika' },
  { code: 'NG', label: 'Nijerya' },
  { code: 'KE', label: 'Kenya' },
  { code: 'ET', label: 'Etiyopya' },
];

export const TR_CITIES: string[] = [
  'Adana', 'Adıyaman', 'Afyonkarahisar', 'Ağrı', 'Aksaray', 'Amasya', 'Ankara',
  'Antalya', 'Ardahan', 'Artvin', 'Aydın', 'Balıkesir', 'Bartın', 'Batman',
  'Bayburt', 'Bilecik', 'Bingöl', 'Bitlis', 'Bolu', 'Burdur', 'Bursa',
  'Çanakkale', 'Çankırı', 'Çorum', 'Denizli', 'Diyarbakır', 'Düzce', 'Edirne',
  'Elazığ', 'Erzincan', 'Erzurum', 'Eskişehir', 'Gaziantep', 'Giresun',
  'Gümüşhane', 'Hakkari', 'Hatay', 'Iğdır', 'Isparta', 'İstanbul', 'İzmir',
  'Kahramanmaraş', 'Karabük', 'Karaman', 'Kars', 'Kastamonu', 'Kayseri',
  'Kilis', 'Kırıkkale', 'Kırklareli', 'Kırşehir', 'Kocaeli', 'Konya',
  'Kütahya', 'Malatya', 'Manisa', 'Mardin', 'Mersin', 'Muğla', 'Muş',
  'Nevşehir', 'Niğde', 'Ordu', 'Osmaniye', 'Rize', 'Sakarya', 'Samsun',
  'Şanlıurfa', 'Siirt', 'Sinop', 'Şırnak', 'Sivas', 'Tekirdağ', 'Tokat',
  'Trabzon', 'Tunceli', 'Uşak', 'Van', 'Yalova', 'Yozgat', 'Zonguldak',
];
