import type { NewsLanguage, NewsSourceType } from '@prisma/client';

export type SeedSource = {
  slug: string;
  name: string;
  homepageUrl: string;
  feedUrl: string;
  logoDomain: string;
  language: NewsLanguage;
  type: NewsSourceType;
  keywordFilter?: string;
};

export const DEFAULT_SOURCES: SeedSource[] = [
  {
    slug: 'marketing-dive',
    name: 'Marketing Dive',
    homepageUrl: 'https://www.marketingdive.com/',
    feedUrl: 'https://www.marketingdive.com/feeds/news/',
    logoDomain: 'marketingdive.com',
    language: 'EN',
    type: 'RSS',
  },
  {
    slug: 'the-drum',
    name: 'The Drum',
    homepageUrl: 'https://www.thedrum.com/',
    feedUrl:
      'https://news.google.com/rss/search?q=site%3Athedrum.com&hl=en-US&gl=US&ceid=US:en',
    logoDomain: 'thedrum.com',
    language: 'EN',
    type: 'GOOGLE_NEWS',
  },
  {
    slug: 'adweek',
    name: 'Adweek',
    homepageUrl: 'https://www.adweek.com/',
    feedUrl: 'https://www.adweek.com/feed/',
    logoDomain: 'adweek.com',
    language: 'EN',
    type: 'RSS',
  },
  {
    slug: 'campaign',
    name: 'Campaign',
    homepageUrl: 'https://www.campaignlive.co.uk/',
    feedUrl:
      'https://news.google.com/rss/search?q=site%3Acampaignlive.co.uk+OR+site%3Acampaignasia.com&hl=en-US&gl=US&ceid=US:en',
    logoDomain: 'campaignlive.co.uk',
    language: 'EN',
    type: 'GOOGLE_NEWS',
  },
  {
    slug: 'marketing-week',
    name: 'Marketing Week',
    homepageUrl: 'https://www.marketingweek.com/',
    feedUrl: 'https://www.marketingweek.com/feed/',
    logoDomain: 'marketingweek.com',
    language: 'EN',
    type: 'RSS',
  },
  {
    slug: 'underconsideration-brandnew',
    name: 'Brand New',
    homepageUrl: 'https://www.underconsideration.com/brandnew/',
    feedUrl:
      'https://news.google.com/rss/search?q=site%3Aunderconsideration.com&hl=en-US&gl=US&ceid=US:en',
    logoDomain: 'underconsideration.com',
    language: 'EN',
    type: 'GOOGLE_NEWS',
  },
  {
    slug: 'fast-company',
    name: 'Fast Company',
    homepageUrl: 'https://www.fastcompany.com/',
    feedUrl: 'https://www.fastcompany.com/latest/rss',
    logoDomain: 'fastcompany.com',
    language: 'EN',
    type: 'RSS',
    keywordFilter: 'brand,branding,marketing,advertising,design,creative,identity,logo,agency,campaign',
  },
  {
    slug: 'digiday',
    name: 'Digiday',
    homepageUrl: 'https://digiday.com/',
    feedUrl: 'https://digiday.com/feed/',
    logoDomain: 'digiday.com',
    language: 'EN',
    type: 'RSS',
    keywordFilter: 'brand,branding,marketing,advertising,agency,campaign,creative,media',
  },
  {
    slug: 'hubspot-marketing',
    name: 'HubSpot Marketing',
    homepageUrl: 'https://blog.hubspot.com/marketing',
    feedUrl: 'https://blog.hubspot.com/marketing/rss.xml',
    logoDomain: 'hubspot.com',
    language: 'EN',
    type: 'RSS',
  },
  {
    slug: 'search-engine-land',
    name: 'Search Engine Land',
    homepageUrl: 'https://searchengineland.com/',
    feedUrl: 'https://searchengineland.com/feed',
    logoDomain: 'searchengineland.com',
    language: 'EN',
    type: 'RSS',
    keywordFilter: 'brand,marketing,seo,ads,advertising,content,strategy,campaign',
  },
  {
    slug: 'branding-strategy-insider',
    name: 'Branding Strategy Insider',
    homepageUrl: 'https://brandingstrategyinsider.com/',
    feedUrl: 'https://brandingstrategyinsider.com/feed/',
    logoDomain: 'brandingstrategyinsider.com',
    language: 'EN',
    type: 'RSS',
  },
  {
    slug: 'ad-age',
    name: 'Ad Age',
    homepageUrl: 'https://adage.com/',
    feedUrl:
      'https://news.google.com/rss/search?q=site%3Aadage.com&hl=en-US&gl=US&ceid=US:en',
    logoDomain: 'adage.com',
    language: 'EN',
    type: 'GOOGLE_NEWS',
  },
  {
    slug: 'creative-review',
    name: 'Creative Review',
    homepageUrl: 'https://www.creativereview.co.uk/',
    feedUrl:
      'https://news.google.com/rss/search?q=site%3Acreativereview.co.uk&hl=en-US&gl=US&ceid=US:en',
    logoDomain: 'creativereview.co.uk',
    language: 'EN',
    type: 'GOOGLE_NEWS',
  },
  {
    slug: 'design-week',
    name: 'Design Week',
    homepageUrl: 'https://www.designweek.co.uk/',
    feedUrl:
      'https://news.google.com/rss/search?q=site%3Adesignweek.co.uk&hl=en-US&gl=US&ceid=US:en',
    logoDomain: 'designweek.co.uk',
    language: 'EN',
    type: 'GOOGLE_NEWS',
  },
  {
    slug: 'its-nice-that',
    name: 'It\'s Nice That',
    homepageUrl: 'https://www.itsnicethat.com/',
    feedUrl:
      'https://news.google.com/rss/search?q=site%3Aitsnicethat.com&hl=en-US&gl=US&ceid=US:en',
    logoDomain: 'itsnicethat.com',
    language: 'EN',
    type: 'GOOGLE_NEWS',
  },
  {
    slug: 'lbb-online',
    name: 'Little Black Book',
    homepageUrl: 'https://www.lbbonline.com/',
    feedUrl:
      'https://news.google.com/rss/search?q=site%3Albbonline.com&hl=en-US&gl=US&ceid=US:en',
    logoDomain: 'lbbonline.com',
    language: 'EN',
    type: 'GOOGLE_NEWS',
  },
  {
    slug: 'pr-week',
    name: 'PRWeek',
    homepageUrl: 'https://www.prweek.com/',
    feedUrl:
      'https://news.google.com/rss/search?q=site%3Aprweek.com&hl=en-US&gl=US&ceid=US:en',
    logoDomain: 'prweek.com',
    language: 'EN',
    type: 'GOOGLE_NEWS',
  },
  {
    slug: 'contagious',
    name: 'Contagious',
    homepageUrl: 'https://www.contagious.com/',
    feedUrl:
      'https://news.google.com/rss/search?q=site%3Acontagious.com&hl=en-US&gl=US&ceid=US:en',
    logoDomain: 'contagious.com',
    language: 'EN',
    type: 'GOOGLE_NEWS',
  },
  {
    slug: 'marketing-turkiye',
    name: 'Marketing Türkiye',
    homepageUrl: 'https://www.marketingturkiye.com.tr/',
    feedUrl: 'https://www.marketingturkiye.com.tr/rss',
    logoDomain: 'marketingturkiye.com.tr',
    language: 'TR',
    type: 'RSS',
  },
  {
    slug: 'mediacat',
    name: 'MediaCat',
    homepageUrl: 'https://mediacat.com/',
    feedUrl: 'https://mediacat.com/feed/',
    logoDomain: 'mediacat.com',
    language: 'TR',
    type: 'RSS',
  },
  {
    slug: 'the-brand-age',
    name: 'The Brand Age',
    homepageUrl: 'https://www.thebrandage.com/',
    feedUrl: 'https://www.thebrandage.com/feed',
    logoDomain: 'thebrandage.com',
    language: 'TR',
    type: 'RSS',
  },
  {
    slug: 'digital-age-tr',
    name: 'Digital Age',
    homepageUrl: 'https://digitalage.com.tr/',
    feedUrl: 'https://digitalage.com.tr/feed',
    logoDomain: 'digitalage.com.tr',
    language: 'TR',
    type: 'RSS',
    keywordFilter: 'marka,pazarlama,reklam,kampanya,iletişim,tasarım,dijital,marketing',
  },
  {
    slug: 'campaign-tr',
    name: 'Campaign Türkiye',
    homepageUrl: 'https://www.campaigntr.com/',
    feedUrl: 'https://www.campaigntr.com/feed',
    logoDomain: 'campaigntr.com',
    language: 'TR',
    type: 'RSS',
  },
  {
    slug: 'techcrunch',
    name: 'TechCrunch',
    homepageUrl: 'https://techcrunch.com/',
    feedUrl: 'https://techcrunch.com/feed/',
    logoDomain: 'techcrunch.com',
    language: 'EN',
    type: 'RSS',
    keywordFilter: 'startup,brand,branding,marketing,founder,vc,funding,series,raised,launches,rebrand',
  },
  {
    slug: 'entrepreneur',
    name: 'Entrepreneur',
    homepageUrl: 'https://www.entrepreneur.com/',
    feedUrl: 'https://www.entrepreneur.com/latest.rss',
    logoDomain: 'entrepreneur.com',
    language: 'EN',
    type: 'RSS',
    keywordFilter: 'brand,branding,marketing,startup,founder,business,growth,strategy,leadership',
  },
  {
    slug: 'inc-magazine',
    name: 'Inc.',
    homepageUrl: 'https://www.inc.com/',
    feedUrl:
      'https://news.google.com/rss/search?q=site%3Ainc.com&hl=en-US&gl=US&ceid=US:en',
    logoDomain: 'inc.com',
    language: 'EN',
    type: 'GOOGLE_NEWS',
    keywordFilter: 'brand,branding,marketing,startup,founder,business,growth,strategy',
  },
  {
    slug: 'sifted',
    name: 'Sifted',
    homepageUrl: 'https://sifted.eu/',
    feedUrl: 'https://sifted.eu/feed',
    logoDomain: 'sifted.eu',
    language: 'EN',
    type: 'RSS',
    keywordFilter: 'startup,founder,raised,funding,series,brand,marketing,launch,vc,acquired',
  },
  {
    slug: 'webrazzi',
    name: 'Webrazzi',
    homepageUrl: 'https://webrazzi.com/',
    feedUrl: 'https://webrazzi.com/feed',
    logoDomain: 'webrazzi.com',
    language: 'TR',
    type: 'RSS',
    keywordFilter: 'girişim,startup,marka,pazarlama,yatırım,kurucu,kampanya,reklam,büyüme,strateji',
  },
  {
    slug: 'pazarlamasyon',
    name: 'Pazarlamasyon',
    homepageUrl: 'https://pazarlamasyon.com/',
    feedUrl: 'https://pazarlamasyon.com/feed',
    logoDomain: 'pazarlamasyon.com',
    language: 'TR',
    type: 'RSS',
  },
  {
    slug: 'google-news-tr-markalasma',
    name: 'Google News — Türkiye',
    homepageUrl: 'https://news.google.com/',
    feedUrl:
      'https://news.google.com/rss/search?q=%22marka%20stratejisi%22%20OR%20%22marka%20kimli%C4%9Fi%22%20OR%20%22marka%20dan%C4%B1%C5%9Fman%22%20OR%20%22rebranding%22%20OR%20%22yeni%20logo%22&hl=tr&gl=TR&ceid=TR:tr',
    logoDomain: 'news.google.com',
    language: 'TR',
    type: 'GOOGLE_NEWS',
    keywordFilter: 'marka,logo,kimlik,rebranding,kampanya,reklam,pazarlama,iletişim',
  },
  {
    slug: 'google-news-branding',
    name: 'Google News — Branding',
    homepageUrl: 'https://news.google.com/',
    feedUrl:
      'https://news.google.com/rss/search?q=branding+OR+%22brand+strategy%22+OR+%22brand+identity%22&hl=en-US&gl=US&ceid=US:en',
    logoDomain: 'news.google.com',
    language: 'EN',
    type: 'GOOGLE_NEWS',
    keywordFilter: 'brand,branding,identity,strategy,marketing',
  },
];

export function logoUrlFor(domain: string): string {
  return `https://www.google.com/s2/favicons?domain=${domain}&sz=128`;
}
